# Generated by Django 3.0.5 on 2020-04-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(verbose_name='Rate Date'),
        ),
        migrations.AddField(
            model_name='book',
            name='Reader',
            field=models.ManyToManyField(to='main_app.Reader'),
        ),
    ]
