# Generated by Django 3.0.5 on 2020-04-08 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200408_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Reader',
            new_name='reader',
        ),
    ]
